name: imprimis-game
base: core22
architectures:
  - build-on: amd64
summary: Imprims, the destroyable world FPS
description: |
  A multiplayer 3D first person shooter built on the Libprimis engine.
grade: stable
confinement: strict
adopt-info: imprimis-game

apps:
  imprimis-game:
    command: bin/desktop-launch $SNAP/imprimis_snap_run
    plugs:
      - network
      - opengl
      - audio-playback
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - screen-inhibit-control
      - home
parts:
  imprimis-game:
    plugin: nil
    override-pull: |
      git clone https://github.com/project-imprimis/libprimis.git --recurse-submodules
      git clone https://github.com/project-imprimis/imprimis.git --recurse-submodules
      snapcraftctl set-version $(git describe --tags --always | sed 's/[^a-zA-Z0-9\.\:\+\~\-]/_/g')
    build-packages:
      - g++
      - make
      - git
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libglew-dev
      - libstdc++-10-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libglu1-mesa
      - libgl1-mesa-dri
      - libglew2.2
      - libpulse0
      - libselinux1
      - libz3-4
      - liblzma5
      - libapparmor1
      - libstdc++-10-dev
    override-build: |
      cd libprimis
      cd src
      make -j8
      cd ../..
      cd imprimis
      cp ../libprimis/src/libprimis.so ./libprimis.so
      make -j8
      cd ..
      cp imprimis/config -r ../install/config
      cp imprimis/media -r ../install/media
      cp imprimis/native_client ../install/native_client
      cp imprimis/imprimis_snap_run ../install/imprimis_snap_run
      cp imprimis/libprimis.so ../install/lib/x86_64-linux-gnu/libprimis.so
      cp ../install/usr/lib/x86_64-linux-gnu/pulseaudio/*.so ../install/usr/lib/x86_64-linux-gnu/
      chmod 777 ../install/imprimis_snap_run
    after:
      - desktop-glib-only
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
